#ifndef NSU_OOP_2021_LABS_HASHTABLEKEYNOTFOUNDEXCEPTION_H
#define NSU_OOP_2021_LABS_HASHTABLEKEYNOTFOUNDEXCEPTION_H

#include <exception>

class HashTableKeyNotFoundException: std::exception {

};


#endif //NSU_OOP_2021_LABS_HASHTABLEKEYNOTFOUNDEXCEPTION_H
